services:
  - type: web
    name: skboy
    env: rust
    plan: free
    buildCommand: cargo build --release
    startCommand: ./target/release/skboy-site
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_PATH
        sync: false
